// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHKxD7bHIhIeWz6NyXAdAwSFEJeBrFI2k',
    appId: '1:962522301327:web:205fdbce6a401234b241fa',
    messagingSenderId: '962522301327',
    projectId: 'signindemo-59e01',
    authDomain: 'signindemo-59e01.firebaseapp.com',
    storageBucket: 'signindemo-59e01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7k9zplS4Vlxn7dnGj4u4kTihQyTht7-4',
    appId: '1:962522301327:android:a7d9e55cb8c96b9db241fa',
    messagingSenderId: '962522301327',
    projectId: 'signindemo-59e01',
    storageBucket: 'signindemo-59e01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMmDgvvHf8k-csM7hACySjFrlmGnktNc',
    appId: '1:962522301327:ios:f70ad2bea333c890b241fa',
    messagingSenderId: '962522301327',
    projectId: 'signindemo-59e01',
    storageBucket: 'signindemo-59e01.firebasestorage.app',
    iosBundleId: 'com.example.googleSigninDemo',
  );
}
